name: Generate terraform docs
on:
  - push

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Render terraform docs and push changes back to main
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          git-push: "true"
          output-file: README.md
          output-method: replace
          recursive: "true"
          working-dir: .
