name: Module tests
on:
  push:
    branches-ignore:
      - main

jobs:
  test-modules:
    name: Test terraform modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: false
